-- Neovim colorscheme - Generated by themey
-- This file is auto-generated. Do not edit manually.

vim.cmd('hi clear')
if vim.fn.exists('syntax_on') then
  vim.cmd('syntax reset')
end

vim.o.termguicolors = true
vim.g.colors_name = 'themey'

-- Define color palette
local colors = {
  background = '#13151c',
  foreground = '#a8b0c8',
  cursor = '#e0b87d',

  black = '#1a1d28',
  red = '#d4825c',
  green = '#5a7a6f',
  yellow = '#c89b5f',
  blue = '#4d6a8a',
  magenta = '#7a6b8e',
  cyan = '#5d8a92',
  white = '#9ca3b8',

  bright_black = '#3a4150',
  bright_red = '#e8a074',
  bright_green = '#729184',
  bright_yellow = '#e0b87d',
  bright_blue = '#6d8eb0',
  bright_magenta = '#9b88ab',
  bright_cyan = '#7aa8b5',
  bright_white = '#c5cce0',
}

-- Helper function to set highlights
local function hi(group, opts)
  local cmd = 'highlight ' .. group
  if opts.fg then cmd = cmd .. ' guifg=' .. opts.fg end
  if opts.bg then cmd = cmd .. ' guibg=' .. opts.bg end
  if opts.style then cmd = cmd .. ' gui=' .. opts.style end
  if opts.sp then cmd = cmd .. ' guisp=' .. opts.sp end
  vim.cmd(cmd)
end

-- Editor highlights
hi('Normal', { fg = colors.foreground, bg = colors.background })
hi('NormalFloat', { fg = colors.foreground, bg = colors.black })
hi('FloatBorder', { fg = colors.bright_black, bg = colors.black })
hi('Cursor', { fg = colors.background, bg = colors.cursor })
hi('CursorLine', { bg = colors.black })
hi('CursorColumn', { bg = colors.black })
hi('LineNr', { fg = colors.bright_black })
hi('CursorLineNr', { fg = colors.yellow, style = 'bold' })
hi('SignColumn', { bg = colors.background })
hi('ColorColumn', { bg = colors.black })
hi('VertSplit', { fg = colors.bright_black })
hi('Visual', { bg = colors.bright_black })
hi('VisualNOS', { bg = colors.bright_black })
hi('Search', { fg = colors.background, bg = colors.yellow })
hi('IncSearch', { fg = colors.background, bg = colors.bright_yellow })
hi('MatchParen', { fg = colors.bright_cyan, style = 'bold' })
hi('Folded', { fg = colors.bright_black, bg = colors.black })
hi('FoldColumn', { fg = colors.bright_black, bg = colors.background })

-- Statusline
hi('StatusLine', { fg = colors.foreground, bg = colors.black })
hi('StatusLineNC', { fg = colors.bright_black, bg = colors.black })
hi('WildMenu', { fg = colors.background, bg = colors.blue })

-- Tabs
hi('TabLine', { fg = colors.bright_black, bg = colors.black })
hi('TabLineFill', { bg = colors.black })
hi('TabLineSel', { fg = colors.foreground, bg = colors.background, style = 'bold' })

-- Popups and menus
hi('Pmenu', { fg = colors.foreground, bg = colors.black })
hi('PmenuSel', { fg = colors.background, bg = colors.blue })
hi('PmenuSbar', { bg = colors.bright_black })
hi('PmenuThumb', { bg = colors.white })

-- Syntax highlighting
hi('Comment', { fg = colors.bright_black, style = 'italic' })
hi('Constant', { fg = colors.magenta })
hi('String', { fg = colors.green })
hi('Character', { fg = colors.green })
hi('Number', { fg = colors.magenta })
hi('Boolean', { fg = colors.magenta })
hi('Float', { fg = colors.magenta })

hi('Identifier', { fg = colors.cyan })
hi('Function', { fg = colors.blue })

hi('Statement', { fg = colors.red })
hi('Conditional', { fg = colors.red })
hi('Repeat', { fg = colors.red })
hi('Label', { fg = colors.red })
hi('Operator', { fg = colors.foreground })
hi('Keyword', { fg = colors.red })
hi('Exception', { fg = colors.red })

hi('PreProc', { fg = colors.yellow })
hi('Include', { fg = colors.blue })
hi('Define', { fg = colors.yellow })
hi('Macro', { fg = colors.yellow })
hi('PreCondit', { fg = colors.yellow })

hi('Type', { fg = colors.yellow })
hi('StorageClass', { fg = colors.yellow })
hi('Structure', { fg = colors.yellow })
hi('Typedef', { fg = colors.yellow })

hi('Special', { fg = colors.cyan })
hi('SpecialChar', { fg = colors.cyan })
hi('Tag', { fg = colors.cyan })
hi('Delimiter', { fg = colors.foreground })
hi('SpecialComment', { fg = colors.bright_black, style = 'italic' })
hi('Debug', { fg = colors.red })

hi('Underlined', { fg = colors.blue, style = 'underline' })
hi('Ignore', { fg = colors.bright_black })
hi('Error', { fg = colors.bright_red, bg = colors.background })
hi('Todo', { fg = colors.yellow, bg = colors.background, style = 'bold' })

-- Diff
hi('DiffAdd', { fg = colors.green, bg = colors.black })
hi('DiffChange', { fg = colors.yellow, bg = colors.black })
hi('DiffDelete', { fg = colors.red, bg = colors.black })
hi('DiffText', { fg = colors.blue, bg = colors.black, style = 'bold' })

-- Git signs
hi('GitSignsAdd', { fg = colors.green })
hi('GitSignsChange', { fg = colors.yellow })
hi('GitSignsDelete', { fg = colors.red })

-- Treesitter highlights
hi('TSAnnotation', { fg = colors.yellow })
hi('TSAttribute', { fg = colors.cyan })
hi('TSBoolean', { fg = colors.magenta })
hi('TSCharacter', { fg = colors.green })
hi('TSComment', { fg = colors.bright_black, style = 'italic' })
hi('TSConditional', { fg = colors.red })
hi('TSConstant', { fg = colors.magenta })
hi('TSConstBuiltin', { fg = colors.magenta })
hi('TSConstMacro', { fg = colors.magenta })
hi('TSConstructor', { fg = colors.blue })
hi('TSError', { fg = colors.bright_red })
hi('TSException', { fg = colors.red })
hi('TSField', { fg = colors.cyan })
hi('TSFloat', { fg = colors.magenta })
hi('TSFunction', { fg = colors.blue })
hi('TSFuncBuiltin', { fg = colors.blue })
hi('TSFuncMacro', { fg = colors.blue })
hi('TSInclude', { fg = colors.blue })
hi('TSKeyword', { fg = colors.red })
hi('TSKeywordFunction', { fg = colors.red })
hi('TSKeywordOperator', { fg = colors.red })
hi('TSLabel', { fg = colors.red })
hi('TSMethod', { fg = colors.blue })
hi('TSNamespace', { fg = colors.yellow })
hi('TSNumber', { fg = colors.magenta })
hi('TSOperator', { fg = colors.foreground })
hi('TSParameter', { fg = colors.cyan })
hi('TSParameterReference', { fg = colors.cyan })
hi('TSProperty', { fg = colors.cyan })
hi('TSPunctDelimiter', { fg = colors.foreground })
hi('TSPunctBracket', { fg = colors.foreground })
hi('TSPunctSpecial', { fg = colors.cyan })
hi('TSRepeat', { fg = colors.red })
hi('TSString', { fg = colors.green })
hi('TSStringRegex', { fg = colors.green })
hi('TSStringEscape', { fg = colors.cyan })
hi('TSSymbol', { fg = colors.cyan })
hi('TSTag', { fg = colors.red })
hi('TSTagDelimiter', { fg = colors.foreground })
hi('TSText', { fg = colors.foreground })
hi('TSStrong', { style = 'bold' })
hi('TSEmphasis', { style = 'italic' })
hi('TSUnderline', { style = 'underline' })
hi('TSStrike', { style = 'strikethrough' })
hi('TSTitle', { fg = colors.blue, style = 'bold' })
hi('TSLiteral', { fg = colors.green })
hi('TSURI', { fg = colors.blue, style = 'underline' })
hi('TSType', { fg = colors.yellow })
hi('TSTypeBuiltin', { fg = colors.yellow })
hi('TSVariable', { fg = colors.foreground })
hi('TSVariableBuiltin', { fg = colors.cyan })

-- LSP highlights
hi('DiagnosticError', { fg = colors.red })
hi('DiagnosticWarn', { fg = colors.yellow })
hi('DiagnosticInfo', { fg = colors.blue })
hi('DiagnosticHint', { fg = colors.cyan })
hi('DiagnosticUnderlineError', { sp = colors.red, style = 'underline' })
hi('DiagnosticUnderlineWarn', { sp = colors.yellow, style = 'underline' })
hi('DiagnosticUnderlineInfo', { sp = colors.blue, style = 'underline' })
hi('DiagnosticUnderlineHint', { sp = colors.cyan, style = 'underline' })

-- Terminal colors
vim.g.terminal_color_0 = colors.black
vim.g.terminal_color_1 = colors.red
vim.g.terminal_color_2 = colors.green
vim.g.terminal_color_3 = colors.yellow
vim.g.terminal_color_4 = colors.blue
vim.g.terminal_color_5 = colors.magenta
vim.g.terminal_color_6 = colors.cyan
vim.g.terminal_color_7 = colors.white
vim.g.terminal_color_8 = colors.bright_black
vim.g.terminal_color_9 = colors.bright_red
vim.g.terminal_color_10 = colors.bright_green
vim.g.terminal_color_11 = colors.bright_yellow
vim.g.terminal_color_12 = colors.bright_blue
vim.g.terminal_color_13 = colors.bright_magenta
vim.g.terminal_color_14 = colors.bright_cyan
vim.g.terminal_color_15 = colors.bright_white
