# Brutalist colors
$background = rgb(0b0b0b)
$foreground = rgb(f2f2f2)
$cursor = rgb(f2f2f2)

$black = rgb(0b0b0b)
$red = rgb(ff5a5a)
$green = rgb(8dff67)
$yellow = rgb(d8d8d8)
$blue = rgb(f2f2f2)
$magenta = rgb(f2f2f2)
$cyan = rgb(f2f2f2)
$white = rgb(f2f2f2)

$bright_black = rgb(444444)
$bright_red = rgb(ff7a7a)
$bright_green = rgb(a5ff87)
$bright_yellow = rgb(f2f2f2)
$bright_blue = rgb(f2f2f2)
$bright_magenta = rgb(f2f2f2)
$bright_cyan = rgb(f2f2f2)
$bright_white = rgb(ffffff)

general {
    col.active_border = $foreground
    col.inactive_border = rgb(444444)
}
