### WINDOWS AND WORKSPACES ###

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

$displayMain = HDMI-A-1
$displaySec = DP-2


windowrule = match:title qswp, float on, center on, size 636 485
windowrule = match:title crosshair.py, float on, size 20 20, move 1270 547

workspace = 1, monitor:$displayMain
workspace = 2, monitor:$displayMain
workspace = 3, monitor:$displayMain
workspace = 4, monitor:$displayMain
workspace = 5, monitor:$displayMain

workspace = 6, monitor:$displaySec
workspace = 7, monitor:$displaySec
workspace = 8, monitor:$displaySec
workspace = 9, monitor:$displaySec
workspace = 10, monitor:$displaySec

device {
  name = wacom-one-by-wacom-s-pen
  transform = 0 
  output=HDMI-A-1
}

